backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Articoli del Blog" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Crea bellissimi contenuti qui
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titolo", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Indirizzo della pagina",
          name: "slug",
          widget: "string",
          hint: "Inizia con /. usa solo caratteri alfanumerici, - e _. Non mettere spazi in nessun caso.",
        }
      - {
          label: "Data di pubblicazione",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "Descrizione SEO", name: "description", widget: "text" }
      - {
          label: "Immagine principale",
          name: "featuredImage",
          widget: "image",
          required: false,
          tagname: "",
        }

      - {
          label: "Corpo",
          name: "body",
          widget: "markdown",
          hint: "Main content goes here.",
        }
  - label: "Pagine"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Indirizzo della pagina",
              name: "slug",
              widget: "hidden",
              default: "/",
            }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - {
              label: "Immagine principale",
              name: "featuredImage",
              widget: "image",
            }
          - { label: "Corpo", name: "body", widget: "markdown" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "CTA text"
                widget: "string"
              - name: "ctaLink"
                label: "CTA Link"
                widget: "string"
      - label: "Chi sono"
        name: "laryart"
        file: "src/content/pages/laryart.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "laryart",
            }
          - {
              label: "Indirizzo della pagina",
              name: "slug",
              widget: "hidden",
              default: "/laryart",
            }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Corpo", name: "body", widget: "markdown" }
      - label: "Privacy"
        name: "privacy"
        file: "src/content/pages/privacy.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "privacy",
            }
          - {
              label: "Indirizzo della pagina",
              name: "slug",
              widget: "hidden",
              default: "/privacy",
            }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Corpo", name: "body", widget: "markdown" }
      - label: "Contatti"
        name: "contatti"
        file: "src/content/pages/contatti.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contatti",
            }
          - {
              label: "Indirizzo della pagina",
              name: "slug",
              widget: "hidden",
              default: "/contatti",
            }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Corpo", name: "body", widget: "markdown" }
  - name: settings
    label: Impostazioni
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Titolo del Sito
                required: true
              - widget: string
                name: titleTemplate
                label: Titolo del Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Indirizzo del sito
                required: true
              - widget: text
                name: description
                label: Descrizione
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false
